---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
          - name: creating VPC
            ec2_vpc_net:
                    name: kubernetes_vpc
                    cidr_block: 10.50.0.0/16
                    region: ap-south-1
                    dns_hostnames: yes
                    tags:
                            module: ec2_vpc_net
                            this: kubernetes_2
            register: vpc_info
            tags:
                    - always
          - name: saving vpc id
            set_fact:
                    vpc_id: "{{ vpc_info.vpc.id }}"
          - name: Create subnet
            ec2_vpc_subnet:
                    state: present
                    vpc_id: "{{vpc_id}}"
                    cidr: 10.50.0.0/16
                    region: ap-south-1
                    az: ap-south-1a
                    tags:
                            mysub: my_kubernet_sub_id
            register: sub_id
          - name: saving fact for subet id
            set_fact:
                    sub_id: "{{sub_id.subnet.id}}"
          - name: Creating gateway
            ec2_vpc_igw:
                    vpc_id: "{{vpc_id}}"
                    state: present
                    region: ap-south-1
                    tags:
                            myvpc: vpc_gw_kubernet
            register: vpc_gw_info
          - name: saving fact for gateway id
            set_fact:
                    gw_id: "{{vpc_gw_info.gateway_id}}"
          - debug: msg="{{gw_id}}"
            tags:
                    - always
          - name: associate route table
            ec2_vpc_route_table:
                    vpc_id: "{{vpc_id}}"
                    region: ap-south-1
                    routes:
                            - dest: 0.0.0.0/0
                              gateway_id: "{{gw_id}}"
            register: public_route_table
          - name: example2 ec2 key
            ec2_key:
                    name: key-pair_aws_kubernetes
                    key_material: "{{ lookup('file', '~/.ssh/my_aws.pub') }}"
                    state: present
          - name: creating security group
            ec2_group:
                    name: my_security_group
                    description: security
                    vpc_id: "{{ vpc_id }}"
                    region: ap-south-1
                    rules:
                            - proto: tcp
                              from_port: 22
                              to_port: 22
                              cidr_ip: 0.0.0.0/0
                    tags:
                            mysgname: sg_kubernetes
            register: sg_id
            #          - name: saving fact for gateway id
            # set_fact:
            #        sg_k8_id: "{{sg_id}}"
          - debug: msg="{{sg_id}}"
          - name: Launching ec2 instance
            ec2_instance:
                    name: "etcd"
                    instance_type: t2.micro
                    image_id: ami-0123b531fc646552f
                    key_name: aws_vpn
                    region: ap-south-1
                    vpc_subnet_id: "{{sub_id}}" 
                    network:
                            assign_public_ip: true
                            private_ip_address: 10.50.0.10
                    tags:
                            type: aws_kubernetes
                    key_name: key-pair_aws_kubernetes
          - name: Creating IAM Role
            iam_role:
                    name: kubernetes_ansible_role_1
                    state: present
                    assume_role_policy_document: "{{ lookup('file','policy.json') }}"
                    description: This is My New Kubernetes role
            register: iam_role_name
          - name: saving fact for iam role name
            set_fact:
                    iam_k8_name: "{{iam_role_name}}"
          - name: Assign a policy called any group
            iam_policy:
                    iam_type: group
                    iam_name: "{{iam_k8_name}}"
                    policy_name: kubernetes_iam_policy
                    state: present
                    policy_document: kubernetes.json
